config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # devise_scope :user do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end
  resources :users
  
  resources :categories do
    resources :tradings
  end  
  root 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(_user)
    # user ||= User.new # guest user (not logged in)
    can :read, :all
    can :add, :all
    # can :destroy, Recipe, user_id: user.id
    # can :destroy, Inventory, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :trading_categories, dependent: :destroy
  has_many :tradings, through: :trading_categories, dependent: :destroy
  validates :name, presence: true, length: { in: 3..100 }
  validates :icon, presence: true, length: { in: 5..300 }

  def total_tradings
    tradings.sum(:amount)
  end
end

app/models/trading.rb
class Trading < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :trading_categories, dependent: :destroy
  has_many :categories, through: :trading_categories, dependent: :destroy
  validates :name, presence: true, length: { in: 3..100 }
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/trading_category.rb
class TradingCategory < ApplicationRecord
  belongs_to :trading
  belongs_to :category
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :transaction_categories, dependent: :destroy

  validates :name, presence: true, length: { in: 3..25 }
  validates :amount, presence: true, numericality: { greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #  , :confirmable
  has_many :tradings, dependent: :destroy
  has_many :categories, dependent: :destroy

  # validates :name, presence: true, length: { in: 3..100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # attr_reader :current_user
  # protect_from_forgery with: :exception
  # include SessionsHelper
  # def logged_in?
  #   session[:user_id]
  # end

  # def require_login
  #   redirect_to login_path unless logged_in?
  # end
  # def user_is_logged_in
  #   if !session[:current_user]
  #       redirect_to login_path
  #   end
  # end

  # def current_user
  #   puts session[:current_user]
  #   return unless session[:user_id]
  #   @current_user ||= User.find(session[:user_id])
  # end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
  end

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || categories_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  def index
    puts session[:current_user]
    @categories = Category.where(author_id: current_user.id)
  end

  def new
    # @images = Dir.glob('app/assets/images/Categories/*.png')
    @images= Dir.glob("#{Rails.root}/app/assets/images/Categories/*.png") 
  end

  def create
    puts 'Parametros new cat'
    puts params
    @category = Category.new(category_params)
    @category.author_id = current_user.id

    if @category.save
      flash[:notice] = 'Category was successfully created.'
    else
      flash[:error] = 'Error creating category'
    end
    redirect_to categories_path
  end

  def update
    if @category.update(category_params)
      flash[:notice] = 'Category was successfully updated.'
    else
      flash[:error] = 'Error updating category'
    end
  end

  def destroy
    puts 'Delete category'
    puts params
    @category = Category.find(params[:id])
    if @category.destroy
      flash[:notice] = 'category was successfully destroyed.'
    else
      flash[:error] = 'Error deleting category'
    end
    redirect_to categories_path
  end

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # session[:user_id]
    # @current_user = User.find(session[:user_id])
    @current_user = current_user
    puts 'Current user'
    puts @current_user
  end
end

app/controllers/tradings_controller.rb
class TradingsController < ApplicationController
  before_action :authenticate_user!
  def index
    # puts 'Params trading'
    # puts params
    @category = Category.includes(:tradings).find(params[:category_id])
  end

  def new
    @category = Category.find(params[:category_id])
  end

  def create
    @trading = Trading.new(trading_params)
    @trading.author_id = current_user.id
    if @trading.save
      @trading_category = TradingCategory.new(category_id: params[:category_id], trading_id: @trading.id)
      @trading_category.save
      flash[:notice] = 'transaction was successfully created.'
    else
      flash[:error] = 'Error creating transaction'
    end
    redirect_to category_tradings_path, category_id: trading_params[:category_id]
  end

  def update
    respond_to do |_format|
      if @trading.update(trading_params)
        flash[:notice] = 'transaction was successfully created.'
      else
        flash[:error] = 'Error creating transaction'
      end
    end
  end

  def destroy
    if @trading.destroy
      flash[:notice] = 'transaction was successfully created.'
    else
      flash[:error] = 'Error creating transaction'
    end
  end

  def trading_params
    params.require(:trading).permit(:name, :amount)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transactions=Transaction.all
  end

  def new
  end

  def create
  end

  def update
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user

  def index
    @current_user = current_user
    # authorize! :read, User
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tradings_helper.rb
module TradingsHelper
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/index.html.erb
<div class="category-container">
   <%if (@categories.any?)%>
        <% @categories.each do |category| %>
            <%= render partial: "shared/category_item", locals: { category: category } %>
        <% end %>        
    <% else %>
        <h5>category records not found!</h5>
    <% end %>
     <%= link_to "New category", new_category_path, class: "btn btn-primary btn-lg btn-block new-category" %>
 </div>

app/views/categories/new.html.erb
<%= form_with(model: Category.new) do |f| %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autocomplete: "name", required: true %>
  </div>
  <div class="field">
      <legend>Select one image:</legend>  
      <div class="images-container" >
      <% @images.each do |image| %>
          <div class="image-select" >
              <%=image_tag asset_path("#{image.split('/').last}")%>
              <%= f.radio_button :icon, "#{image.split('/').last}"%> 
          </div>
       <% end %>
       </div>
</div>
  <div class="actions">
    <%= f.submit "Save", class: "btn btn-info" %>
  </div>
<% end %>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/home/index.html.erb
<div class="splash">
  <%if current_user%>
    <h2>Hi, <%= current_user.name %>!</h2>
  <% end %>
    <img class="image-category" src="<%= image_path("icons8-market-64.png") %>" alt="icon app"/>
  <h1>My Money</h1>
  <div class="splash_buttons">
    <%if user_signed_in?%>
    <%= link_to button_to "Categories", categories_path, class:"btn btn-info", method: :get %>
    <%= button_to "Sign Out", destroy_user_session_path, class: "btn btn-primary", method: :delete %>
    <% else %>
      <%= button_to "Sign In", new_user_session_path, class: "btn btn-info" %>
      <%= button_to "Sign Up", new_user_registration_path, class: "btn btn-info", method: :get %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Money</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script> 
    <%= javascript_include_tag "application" %>
    <%# <%= javascript_importmap_tags %> 
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> 
  </head>

  <body>
    <%= render "shared/header" %> 
    <div class="container ">
      <div class="center-container">
       <div class="form-container">
        <div class="row-header">
          <%= button_to  "<", root_path, class: "btn btn-info", method: :get %>
        </div>
          <%= yield %>
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_category_item.html.erb
<div class="category-item">
    <div class="category-left">
    <img class="image-category-item" src="<%= image_path("#{category.icon.split('/').last}".gsub("\\", "/").gsub("app/assets/images","/assets")) %>" alt="icon category"/>
    </div>
    <div class="category-center">
        <h3 class="category-name"><%= link_to "#{category.name}", category_tradings_path(category) %> </h3>
        <label><%=category.created_at.strftime('%d %b %Y')%> </label> 
    </div>
    <div class="category-right">
        <label><%=category.total_tradings %> </label>
    </div>
    <div class="delete-category">
      <%= button_to "Delete", category, method: :delete, class: "btn btn-info" %>
    </div>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">My Money</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Categories", categories_path, class: "nav-link" %>
        </li>
      <%if user_signed_in?%>
        <li class="nav-item">
            <%= button_to  "Sign Out", destroy_user_session_path, class: "btn btn-primary", method: :delete %>
        </li>
      <% else %>
        <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
      
      </ul>
      <%if user_signed_in?%>
          <form class="d-flex">
            <input class="form-control me-5" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-info" type="submit">Search</button>
          </form>
       <% end %>
    </div>
  </div>
</nav>

app/views/shared/_trading_item.html.erb
<div class="trading-item">
    <div class="trading-left">
        <p><%= trading.name %> </p>
    </div>    
    <div class="trading-center">
        <label><%= trading.created_at.strftime('%d %b %Y') %> </label>
    </div>
    <div class="trading-right">
        <label class="amount"><%= trading.amount %> </label>
    </div>
</div>

app/views/shared/_transaction_item.html.erb
<div class="trading-item">
    <div class="trading-left">
        <img class="image-trading" src="<%= trading.icon%>" alt="icon trading"/>
    </div>
    <div class="trading-center">
        <p><%= trading.name %> </p>
        <label><%= trading.created_at %> </label>
    </div>
    <div class="trading-right">
        <label class="description"><%= trading.amount %> </label>
    </div>
</div>

app/views/tradings/create.html.erb
<h1>Tradings#create</h1>
<p>Find me in app/views/tradings/create.html.erb</p>

app/views/tradings/destroy.html.erb
<h1>Tradings#destroy</h1>
<p>Find me in app/views/tradings/destroy.html.erb</p>

app/views/tradings/index.html.erb
<div class="trading-container">
    <div class="category-item-trading">
        <div class="category-left">
            <img class="image-category-item" src="<%= image_path("#{@category.icon.split('/').last}".gsub("\\", "/").gsub("app/assets/images","/assets")) %>" alt="icon category"/>
        </div>
        <div class="category-center">
            <h3><%= @category.name %> </h3>
        </div>
        <div class="category-right">
            <label><%=@category.total_tradings %> </label>
        </div>
    </div>
 
   <%if (@category.tradings.any?)%>
        <% @category.tradings.each do |trading| %>
            <%= render partial: "shared/trading_item", locals: { trading: trading } %>
        <% end %>        
    <% else %>
        <h5>Trading records not found!</h5>
    <% end %>
    <%= link_to "New transaction", new_category_trading_path(@category), class: "btn btn-primary btn-lg btn-block new-category" %>
</div>

app/views/tradings/new.html.erb
<div class="new-trading">
  <div class="category-center">
      <h3>Category: <%= @category.name %> </h3>
  </div>
  <%= form_with(model: Trading.new, url: { action: "create" } , method: :post,) do |f| %>
     <%=f.hidden_field :category_id, :value => "#{@category.id}", readonly: true%>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name, autocomplete: "name", required: true %>
    </div>

    <div class="field">
      <%= f.label :amount %><br />
      <%# <%= form.select :amount, , value: @group.icon, required: true, class: "select_icon_menu" %>
      <%= f.text_field :amount, autocomplete: "amount", required: true %>
    </div>
  <div class="actions">
      <%= f.submit "Save", class: "btn btn-info" %>
    </div>
  <% end %>
</div>

app/views/tradings/update.html.erb
<h1>Tradings#update</h1>
<p>Find me in app/views/tradings/update.html.erb</p>

app/views/transactions/new.html.erb
<%= form_with(model: Transaction.new) do |form| %>

  <div class="field">
    <%= form.text_field :name, value: @group.name, placeholder: "Name", required: true, class: "form_field" %>
  </div>

  <div class="select_icon">
    <%= form.label :icon, 'Select Icon:', class: "select_icon_label" %>
    <%= form.select :icon, ["✈️", "🎮", "📚", "🏥", "🏈", "🎬", "🏠", "🐶", "🍻", "🍔", "🚗", "🖥"], value: @group.icon, required: true, class: "select_icon_menu" %>
  </div>

  <div class="actions">
    <%= form.submit "Save", class: "app_button green_button" %>
  </div>
<% end %>